export default {
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "44d7f14c": [() => import(/* webpackChunkName: "44d7f14c" */ "@site/docs/module-1/I18N_WORKFLOW.md"), "@site/docs/module-1/I18N_WORKFLOW.md", require.resolveWeak("@site/docs/module-1/I18N_WORKFLOW.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "6c7dc579": [() => import(/* webpackChunkName: "6c7dc579" */ "@site/i18n/ur/docusaurus-plugin-content-docs/current/module-1/00-intro.md"), "@site/i18n/ur/docusaurus-plugin-content-docs/current/module-1/00-intro.md", require.resolveWeak("@site/i18n/ur/docusaurus-plugin-content-docs/current/module-1/00-intro.md")],
  "7b51d1da": [() => import(/* webpackChunkName: "7b51d1da" */ "@generated/docusaurus-plugin-content-docs/default/p/hackathon-book-ur-docs-b35.json"), "@generated/docusaurus-plugin-content-docs/default/p/hackathon-book-ur-docs-b35.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/hackathon-book-ur-docs-b35.json")],
  "7ddff0c6": [() => import(/* webpackChunkName: "7ddff0c6" */ "@site/docs/module-1/README.md"), "@site/docs/module-1/README.md", require.resolveWeak("@site/docs/module-1/README.md")],
  "a76d8bc2": [() => import(/* webpackChunkName: "a76d8bc2" */ "@site/i18n/ur/docusaurus-plugin-content-docs/current/module-1/01-communication.md"), "@site/i18n/ur/docusaurus-plugin-content-docs/current/module-1/01-communication.md", require.resolveWeak("@site/i18n/ur/docusaurus-plugin-content-docs/current/module-1/01-communication.md")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "b8039f88": [() => import(/* webpackChunkName: "b8039f88" */ "@site/docs/docs.md"), "@site/docs/docs.md", require.resolveWeak("@site/docs/docs.md")],
  "bac8f337": [() => import(/* webpackChunkName: "bac8f337" */ "@site/docs/module-1/VERIFICATION_LOG.md"), "@site/docs/module-1/VERIFICATION_LOG.md", require.resolveWeak("@site/docs/module-1/VERIFICATION_LOG.md")],
  "ff2537fb": [() => import(/* webpackChunkName: "ff2537fb" */ "@site/i18n/ur/docusaurus-plugin-content-docs/current/module-1/02-python-agents.md"), "@site/i18n/ur/docusaurus-plugin-content-docs/current/module-1/02-python-agents.md", require.resolveWeak("@site/i18n/ur/docusaurus-plugin-content-docs/current/module-1/02-python-agents.md")],};
